options:
  spellcheck: false
  lineNumbers: true
  askImageFilename: true
  overwriteImages: true
  imagePrefix: pasted-image
  imagePath: images/
editor:
  inputStyle: contenteditable
  spellcheck: false
  lineNumbers: true
